### ISSUE TITLE
Waifu Pixiv Telegram Webhook

### ISSUE THREAD

**Issue by animemoeus** [animemoeus/mono-backend#48]
Since Elon Musk takeover the Twitter, we can't access the API to get tweet details for free.

This makes the waifu database outdated because there is no new data anymore.

https://github.com/animemoeus/waifu-animemoeus/issues/262

---

To fix this problem, we need to get waifu from a new data source (Pixiv).

**Comment by jeydinpham** [comment]
iirc, pixiv has an option to filter out ai generated posts in the search results, could we utilize that to hide ai generated posts in the api
