### ISSUE TITLE
Reduce AI Generated Image for Waifu

### ISSUE THREAD

**Issue by animemoeus** [animemoeus/mono-backend#55]
iirc, pixiv has an option to filter out ai generated posts in the search results, could we utilize that to hide ai generated posts in the api

_Originally posted by @Jeydin21 in https://github.com/animemoeus/backend/issues/48#issuecomment-1843519482_

**Comment by animemoeus** [comment]
Discord has blocked our free image server storage 🗿

Will discontinue the `waifu` app 🥲

**Comment by jeydinpham** [comment]
Awww nooooo I was hoping they would never have pushed that stupid update
